### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by makeukus** [TikHubIO/TikHub_API_PyPi#1]
Running test : API.get_douyin_profile_videos()
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tikhub\api.py", line 254, in get_douyin_profile_videos
    async with session.get(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 637, in _request
    break
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\helpers.py", line 720, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\软件\douyinProject\douyin_monitor.py", line 81, in <module>
    asyncio.run(async_test())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\软件\douyinProject\douyin_monitor.py", line 62, in async_test
    aweme_list = await api.get_douyin_profile_videos(douyin_user_url, 20)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\__init__.py", line 363, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x25d2dd71c40 state=finished raised TimeoutError>]

Process finished with exit code 1

**Comment by Evil0ctal** [comment]
Looks like Douyin API has an issue, I will fix it later.

**Comment by makeukus** [comment]
> Looks like Douyin API has an issue, I will fix it later.

OK
