### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by makeukus** [TikHubIO/TikHub_API_PyPi#2]
API.get_douyin_profile_videos()  Error
It only worked a few times, and then it didn't work

Running test : API.get_douyin_profile_videos()
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tikhub\api.py", line 261, in get_douyin_profile_videos
    aweme_list.extend(response.get('aweme_list'))
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\软件\douyinProject\douyin_monitor.py", line 90, in <module>
    asyncio.run(async_test())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\软件\douyinProject\douyin_monitor.py", line 64, in async_test
    aweme_list = await api.get_douyin_profile_videos(douyin_user_url, 20)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\tenacity\__init__.py", line 363, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x25771af4f40 state=finished raised TypeError>]

**Comment by Evil0ctal** [comment]
Will fix soon.
