### ISSUE TITLE
测试用例跑不下去

### ISSUE THREAD

**Issue by dotaxl** [TikHubIO/TikHub_API_PyPi#6]
Running test : API.get_douyin_profile_liked_videos()
Traceback (most recent call last):
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\tenacity\_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\tikhub\api.py", line 294, in get_douyin_profile_liked_videos
    aweme_list.extend(response.get('aweme_list'))
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\PycharmProjects\pythonProject\TikTok\douyin\Main.py", line 82, in <module>
    asyncio.run(async_test())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\PycharmProjects\pythonProject\TikTok\douyin\Main.py", line 68, in async_test
    aweme_list = await api.get_douyin_profile_liked_videos(douyin_user_url, 20)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\tenacity\_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\tenacity\_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\tenacity\__init__.py", line 363, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1ada879d8e0 state=finished raised TypeError>]

**Comment by Evil0ctal** [comment]
由于服务器现在不是很稳定导致的，已经在着手修复了。
